FROM ubuntu : latest

#set working directory in the image
WORKDIR /app

#copy the file from the host file system 
COPY ./app

#insatall the nessary package
RUN apt-get  update && apt-get install -y pyhton3 pyhton3-pip

# set environment variable
ENV NAME WORLD

#run a commond to start the application
CMD ["python3","hello.py"]



